name: Build and Push Qt 6.7.3 ARM64 Image

on:
  workflow_dispatch:   # manually trigger builds


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_PACKAGE_WRITE_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/qt-6.7.3-arm64:latest
            ghcr.io/${{ github.repository_owner }}/qt-6.7.3-arm64:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
